
version: "3"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: es
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - esdata1:/usr/share/elasticsearch/data
  web:
    image: helenoninjaki/hellon
    command: python3 hellon.py
    depends_on:
      - es
    ports:
      - 0000:5000
    volumes:
      - ./flask-app:/opt/hellon
volumes:
    esdata1:
      driver: local
